### ISSUE TITLE
Generify `json-1-validate` so it can be used as a resuable workflow in other repos

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/build-ci#104]
The `json-1-validate` workflow is so close to being generic and reusable. Make it a callable reusable workflow for other repos that might make use of json validation.

Should be a relatively small fix(tm). 

References #100 (specifically https://github.com/ACCESS-NRI/build-ci/pull/100/files#r1336779968 )!

**Comment by aidanheerdegen** [comment]
Could optionally pass a path to check to make it functionally exactly the same as current functionality.
