### ISSUE TITLE
Add CICE5 base image

### ISSUE THREAD

**Issue by Quartzer2** [ACCESS-NRI/build-ci#13]

**Comment by Quartzer2** [comment]
Currently the Build and push Docker image step is failing with

Error: buildx failed with: ERROR: failed to solve: process "docker-shell spack -d install --only dependencies ${PACKAGE}%${COMPILER_NAME}@${COMPILER_VERSION}" did not complete successfully: exit code: 1

**Comment by Quartzer2** [comment]
Still having some trouble with the base package build via the github workflow. @echus suggested trying locally which I've now done (after setting up a sensible docker environment).

Not sure why that variant isn't there in parallelio 2.5.9. Maybe @harshula or @echus could provide some guidance. Would be much appreciated.

...

OK, getting the same from the docker "build" instance.

RuntimeError: variant "shared" not found in package "parallelio" [required from package "cice5"]

And does run from my local (not docker), and just confirming...

`Local: spack info parallelio
...
Variants:
    Name [Default]          When                              Allowed values          Description
    ====================    ==============================    ====================    ==================================================
...
    shared [on]             --                                on, off                 Build shared libraries
...`

and similar spack info from the docker "build" image has no "shared" variant".

**Comment by CodeGat** [comment]
@Quartzer2 was this completed?
