### ISSUE TITLE
Add CABLE to models.json

### ISSUE THREAD

**Issue by SeanBryan51** [ACCESS-NRI/build-ci#146]

**Comment by CodeGat** [comment]
Hey @SeanBryan51 - for the `models.json`, what are the packages that you would like to install for `cable` called?

**Comment by SeanBryan51** [comment]
Probably just the `cable` package. Package dependencies don't need to be listed right?

The SPD is here for reference: https://github.com/ACCESS-NRI/spack-packages/blob/main/packages/cable/package.py
