### ISSUE TITLE
`intel@2021.4.0` and `intel@2021.10.0` aren't being found during `spack` installs

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/build-ci#152]
Now, after `intel@2021.2.1` was lost to the compiler black hole, more have been lost. This means that we cannot build any Docker images that use anything < `intel@2023.x`, which is a massive jump. This can be tested by running `docker build --target=dev -f containers/Dockerfile.base-spack containers/ --build-arg="COMPILER_VERSION=2021.4.0" -t dev:intel2021.4.0`

Some solutions:
* Try and push up a compiler install into our AWS bucket, and install it from there early in all the `Dockerfile.base-spack`s. This has implications for @harshula dev image, because building `base-spack` would require credentials to read from our AWS bucket, even when creating the dev image, or else we cannot install the compilers. 
* Install the compiler on the rocky8 image itself with a package manager (`yum`), and `spack compiler find` it?
* Ask intel why we can't get the compilers from their sources...?
* Some other solution...

**Comment by aidanheerdegen** [comment]
Scott has seen similar issues. His fix was to just update to the latest version (`2021.9`). It might be that the package is still there, but under a different URL?

What versions of the compiler are available with `yum`?

FYI this is the Intel page specifying all the ways to install the intel oneAPI toolkits

https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2023-1/install-using-package-managers.html

**Comment by CodeGat** [comment]
It fails to install `intel-basekit` at `2021.4.0`, similar to `spack`, with:
```
Public key for intel-oneapi-tbb-common-devel-2021.4.0-2021.4.0-643.noarch.rpm is not installed. Failing package is: intel-oneapi-tbb-common-devel-2021.4.0-2021.4.0-643.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
Public key for intel-oneapi-tbb-devel-2021.4.0-2021.4.0-643.x86_64.rpm is not installed. Failing package is: intel-oneapi-tbb-devel-2021.4.0-2021.4.0-643.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

**Comment by CodeGat** [comment]
Attempted again, and same thing:
```
Intel® oneAPI repository                                                                                                                 13 kB/s | 943  B     00:00    
Importing GPG key 0x53D04109:
 Userid     : "CN=Intel(R) Software Development Products"
 Fingerprint: E9BF 0AFC 46D6 E8B7 DA58 82F1 BAC6 F0C3 53D0 4109
 From       : https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
Is this ok [y/N]: y
Key imported successfully
Import of key(s) didn't help, wrong key(s)?
```

**Comment by harshula** [comment]
Hi @CodeGat , @penguian referred me to: https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-fortran-compiler-release-notes.html . As I mentioned during the meeting, the newer Intel oneAPI releases appear to contain an Intel Classic Compiler (ifort) with a `2021` version number. What happens when you try to install a `2023` or `2024` Intel Compiler package?

* New Features in ifx 2024.0.0 and ifort 2021.11.0

* New in Intel® Fortran Compiler Classic and Intel® Fortran Compiler oneAPI 2023.2 Release: Intel Fortran Compiler (ifx) version 2023.2.0 & Intel Fortran Compiler Classic (ifort) version 2021.10.0 (https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-fortran-compiler-release-notes-2023.html)
* New in Intel® Fortran Compiler Classic and Intel® Fortran Compiler oneAPI 2022.3.1 Release: ifort version 2021.7.1 (https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-fortran-compiler-release-notes-2022.html)

**Comment by harshula** [comment]
Bug: https://github.com/spack/spack/issues/43262
Fix: https://github.com/spack/spack/pull/43286
Workaround: `--build-arg COMPILER_VERSION=2023.1.0` , Caveat: Intel oneAPI `2023.1.0` contains ifort `intel@2021.9.0`. We would need to modify the Dockerfile to handle the version mismatch. Best option is to backport the fix to the release branches.

**Comment by harshula** [comment]
Intel compilers installed on Gadi:
```
$ module avail intel-compiler*
-------------------------- /apps/Modules/modulefiles ---------------------------
intel-compiler-llvm/2022.0.0  intel-compiler/2020.2.254  
intel-compiler-llvm/2022.1.0  intel-compiler/2020.3.304  
intel-compiler-llvm/2022.2.0  intel-compiler/2021.1.1    
intel-compiler-llvm/2023.0.0  intel-compiler/2021.2.0    
intel-compiler-llvm/2023.2.0  intel-compiler/2021.3.0    
intel-compiler-llvm/2024.0.2  intel-compiler/2021.4.0    
intel-compiler/2019.3.199     intel-compiler/2021.5.0    
intel-compiler/2019.4.243     intel-compiler/2021.6.0    
intel-compiler/2019.5.281     intel-compiler/2021.7.0    
intel-compiler/2020.0.166     intel-compiler/2021.8.0    
intel-compiler/2020.1.217     intel-compiler/2021.10.0   
```

**Comment by harshula** [comment]
Intel oneAPI package `2023.2.0` contains ifort `2021.10.0`:
```
$ /apps/intel-ct/2023.2.0/compiler-llvm/linux/bin/intel64/ifort -v
ifort version 2021.10.0
```

**Comment by CodeGat** [comment]
Hey @harshula I can't install that compiler in `spack`. I get `1. Cannot satisfy 'intel-oneapi-compilers@2023.2.0'` when running `RUN spack install ${SPACK_ENV_COMPILER_PACKAGE}@${SPACK_ENV_COMPILER_VERSION} arch=${SPACK_ENV_ARCH}`

**Comment by harshula** [comment]
Same here. It's in releases/v0.21 not releases/v0.20.

**Comment by harshula** [comment]
I'll fix this, I'll let you know when it's ready for review.

**Comment by harshula** [comment]
Hi @CodeGat , I'll fix this, I'll let you know when it's ready for review.

**Comment by harshula** [comment]
```
$ /apps/intel-ct/2023.0.0/compiler-llvm/linux/bin/intel64/ifort -v
ifort version 2021.8.0
```

**Comment by harshula** [comment]
* 2023.0.0 uses the lowercase `irc_nas`!
* I think Intel may have fixed the directory lowercase to uppercase issue.

**Comment by harshula** [comment]
We can use `%intel@2021.2.0` again in the Docker image with Spack v0.20 and v0.21, after the following PRs:
* https://github.com/ACCESS-NRI/build-ci/pull/154
* https://github.com/ACCESS-NRI/spack-config/pull/27

**Comment by harshula** [comment]
Additional flexibility has been added when choosing an Intel legacy compiler in:
* https://github.com/ACCESS-NRI/build-ci/pull/155

**Comment by harshula** [comment]
The version number mapping between oneapi and classic is contained in `var/spack/repos/builtin/packages/intel-oneapi-compilers-classic/package.py`
```
    # Versions before 2021 are in the `intel` package
    # intel-oneapi versions before 2022 use intel@19.0.4
    for ver, oneapi_ver in {
        "2021.1.2": "2021.1.2",
        "2021.2.0": "2021.2.0",
        "2021.3.0": "2021.3.0",
        "2021.4.0": "2021.4.0",
        "2021.5.0": "2022.0.1:2022.0.2",
        "2021.6.0": "2022.1.0",
        "2021.7.0": "2022.2.0",
        "2021.7.1": "2022.2.1",
        "2021.8.0": "2023.0.0",
        "2021.9.0": "2023.1.0",
        "2021.10.0": "2023.2.4",
        "2021.11.1": "2024.0.2",
    }.items():
        # prefer 2021.10.0 because it is the last one that has a C compiler
        version(ver, preferred=(ver == "2021.10.0"))
        depends_on("intel-oneapi-compilers@" + oneapi_ver, when="@" + ver, type="run")
```
