### ISSUE TITLE
Combine base-spack and build image jobs in single workflow

### ISSUE THREAD

**Issue by echus** [ACCESS-NRI/build-ci#16]
No reason to have these in separate workflows - no idea why I made them so :sweat_smile:.

Combine jobs from [base-spack](https://github.com/ACCESS-NRI/build-ci/blob/main/.github/workflows/build-and-push-image-base-spack.yml) and [build](https://github.com/ACCESS-NRI/build-ci/blob/main/.github/workflows/build-and-push-image-build.yml) workflows.

[build](https://github.com/ACCESS-NRI/build-ci/blob/main/.github/workflows/build-and-push-image-build.yml) job should wait for base-spack finish before executing (`needs: build-and-push-image-base-spack`).

**Comment by CodeGat** [comment]
Do you think that there could be reasons to run one and not the other? For example, rebuilding the images with an existing spack_packages tag (that already has been built and packaged up)?

**Comment by CodeGat** [comment]
Parking this one for now - going to get @echus opinion on keeping the two workflows separate as new features are coming in that rely on only one of the two running - for example, where we have an existing tagged/main spack_packages that we want to use, and only want to update the image builds.
