### ISSUE TITLE
Support for spack builds with non-default versions

### ISSUE THREAD

**Issue by anton-seaice** [ACCESS-NRI/build-ci#183]
Several access-nri spack packages use the version field to specify different build options. The build-ci currently only supports building the default version for pull_requests.

For example, in the mom5 spack package recipe, we have a master version (for access-om2) and versions for access-esm1.5 and access-esm1.6. The access-esm versions are built from the matching access-esm branch in the mom repository, per these lines in the recipe:

```
    version("master", branch="master", preferred=True)
    version("access-esm1.5", branch="access-esm1.5")
    version("access-esm1.6", branch="master")
```
(https://github.com/ACCESS-NRI/spack-packages/blob/ff2fbc0a9680118a805a0577edbe03008c5346ae/packages/mom5/package.py#L19C1-L22C46)

These versions can be used to define different dependencies and build options.

When new-PRs are created to the access-esm1.5 branch the new PR should be built using the spack version of `@git.commit=access-esm1.5` and when new-PRs are created to master, is should be built using both versions of `@git.commit` and `@git.commit=access-esm1.6`

I think this line needs support for an additional option for the "right-hand side" version from the spack version field.
https://github.com/ACCESS-NRI/build-ci/blob/6cbcde11ef232f521f2cceed0bc653cd037a90c4/.github/workflows/model-1-build.yml#L113

**Comment by CodeGat** [comment]
Working on this now, thanks for bringing it to my attention @anton-seaice
