### ISSUE TITLE
Investigate caching docker build images in build-ci repo

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/build-ci#20]
Docker Images don't seem to be caching very well when running GitHub actions. Potentially this could be because the base image (spack_packages) is constantly changing and therefore any images on top of it must be rebuilt form scratch.

Investigate possible solutions:
- Check if there are any caching options in the Github Actions syntax itself - https://docs.docker.com/build/cache/backends/gha/ and https://github.com/marketplace/actions/docker-layer-caching
- Make the environment setup (`apt-get`) it's own image, meaning it will be snapshotted and won't need to be rebuilt.
- Determine if there is a need for multiple image layers at all - could we just have an image with all of the models dependencies installed, and use `spack activate <model_environment>` as a build arg?
   - Pros: amalgamation into a single image and easy switching between dependencies with `spack activate`, potential for a bit more build caching
   - Cons: Every time a model (dependency) is changed, this large one will have to be rebuilt. 

The ramblings of a madman...
![image](https://github.com/ACCESS-NRI/build-ci/assets/45781416/3f9733b9-1f93-4658-b498-a366cf256fec)

**Comment by aidanheerdegen** [comment]
See also this issue https://github.com/ACCESS-NRI/build-ci/issues/8

**Comment by CodeGat** [comment]
Closing as this issue is better described in #9 - the info here will be useful, however
