### ISSUE TITLE
Bootstrapping spack and pre-built spack containers

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/build-ci#3]
Currently the spack as installed requires bootstrapping:

https://github.com/ACCESS-NRI/oasis3-mct/actions/runs/3700828828/jobs/6269599485#step:3:8
```
==> Bootstrapping clingo from pre-built binaries
[5](https://github.com/ACCESS-NRI/oasis3-mct/actions/runs/3700828828/jobs/6269599485#step:3:6)
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-idkenmhnscjlu5gjqhpcqa4h7o2a7aow.spec.json
[6](https://github.com/ACCESS-NRI/oasis3-mct/actions/runs/3700828828/jobs/6269599485#step:3:7)
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-idkenmhnscjlu5gjqhpcqa4h7o2a7aow.spack
[7](https://github.com/ACCESS-NRI/oasis3-mct/actions/runs/3700828828/jobs/6269599485#step:3:8)
==> Installing "clingo-bootstrap@spack%gcc@10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-x86_64" from a buildcache
```

Not quite sure why, as spack is bootstrapped when the container is created. It might be because the information about bootstrapping is stored in `~/.spack` by default

The [spack configuration docs](https://spack.readthedocs.io/en/v0.19.0/configuration.html#overriding-local-configuration) suggest the following settings for a CI environment:
```bash
export SPACK_DISABLE_LOCAL_CONFIG=true
export SPACK_USER_CACHE_PATH=/tmp/spack
```
In this case the `SPACK_USER_CACHE_PATH` should be somewhere that gets stored in the container so it can be reused in the build stage.

Somewhat related, but spack has containers with `spack` pre-installed available on ghcr.io

https://spack.readthedocs.io/en/v0.19.0/containers.html

https://github.com/orgs/spack/packages?repo_name=spack

The containers above do a separate bootstrap step, e.g.

https://github.com/spack/spack/actions/runs/3709547299/jobs/6288272024#step:5:75

**Comment by echus** [comment]
Ah, apologies, forgot this was open. This is fixed by https://github.com/ACCESS-NRI/build-ci/commit/5f68e612cb3b41a0a4bd968bc3d6d27555a914a9. I'm running `spack bootstrap now` in our base spack container which has the same result.
