### ISSUE TITLE
Allow end user to input spack_packages version via Github Actions UI

### ISSUE THREAD

**Issue by echus** [ACCESS-NRI/build-ci#39]
This would be really useful for testing the actual model compilation CI runs without polluting model repo commit history.

Likely dependent on the solution for triggering workflows remotely from model repos, posting this now so it can be kept in mind for later.

**Comment by CodeGat** [comment]
Hey @echus - can't this be done via https://github.com/ACCESS-NRI/build-ci/actions/workflows/notified-of-spack-packages-update.yml in the `build-ci` repo? Or do you mean from the `spack_pacakges` repo?

**Comment by echus** [comment]
> Hey @echus - can't this be done via https://github.com/ACCESS-NRI/build-ci/actions/workflows/notified-of-spack-packages-update.yml in the `build-ci` repo? Or do you mean from the `spack_pacakges` repo?

I mean the workflows doing the actual model compilation testing inside model repos - e.g. https://github.com/ACCESS-NRI/oasis3-mct/blob/master/.github/workflows/test-build.yml

**Comment by CodeGat** [comment]
Yep, so if I'm understanding correctly theres now an optional (default to `main`) input for `spack-packages-version` in the build-package.yml workflow here: https://github.com/ACCESS-NRI/build-ci/blob/68d57a6156762e758d1b4cb2f63f6de0b773348e/.github/workflows/build-package.yml#L21, so it should be there

**Comment by echus** [comment]
Yep, this is just a note to implement the workflow_dispatch input in each of those workflows so we can specify it via the UI.

**Comment by echus** [comment]
> Ohh, I understand - so there should be a worklow_dispatch input for `spack-packages-version` in each models workflow, so it can use the `with.spack-packages-version` stuff.

Beat me to it. :laughing:

**Comment by CodeGat** [comment]
Although, what would be the rationale for testing model compilation runs outside of a PR?

**Comment by CodeGat** [comment]
Closing this issue for now as the PR triggers would eliminate the need to run your own builds, but we can revisit this in the future.
