### ISSUE TITLE
Trigger image rebuilds on ACCESS-NRI/spack_packages updates

### ISSUE THREAD

**Issue by echus** [ACCESS-NRI/build-ci#4]
Thanks @harshula for the suggestion.

We want to trigger our build images to rebuild whenever ACCESS-NRI/spack_packages has a relevant package file update. For example, if libaccessom2.py is updated we want to rebuild all libaccessom2 build images.

For a first pass implementation just a blanket rebuild on any push to spack_packages would be fine. 

Ideally we would check what package files are updated and only trigger the relevant image rebuild. Will need to handle dependencies (e.g. datetime-fortran, etc) somehow in this as well.

See https://github.com/orgs/community/discussions/26323 for an example of how to trigger workflows from an external repository.

**Comment by micaeljtoliveira** [comment]
Another way to ensure one has the latest version of ACCESS-NRI/spack_packages when building a package would be to move this:
```
# Set up ACCESS Spack package repo
RUN git clone https://github.com/ACCESS-NRI/spack_packages.git $SPACK_PACKAGES_ROOT
COPY repos.yaml $SPACK_ROOT/etc/spack/repos.yaml
```
from [Dockerfile.base-spack](https://github.com/ACCESS-NRI/build-ci/blob/main/containers/Dockerfile.base-spack) to [Dockerfile.build](https://github.com/ACCESS-NRI/build-ci/blob/main/containers/Dockerfile.build).

**Comment by CodeGat** [comment]
I'd be happy to pick up this ticket, but I'd require #6 to be merged first as it has changes to the cloning rules of spack_packages
