### ISSUE TITLE
Refactor names of dependency images to use tags instead of a long name

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/build-ci#45]
**Description**
Dependency image names are becoming quite long as there are more moving parts. Right now, an image name is `container-name: access-nri/build-${{ matrix.package }}-${{ matrix.compiler.name }}${{ matrix.compiler.version }}-${{ github.event.inputs.spack-packages-version }}` (for example, `build-mom5-intel2021.1.2-2023.07.25`, and longer for branch-based `spack_packages` versions).
Consider using multiple `docker tag`s for each image that specifies the compiler name and version, and spack_packages version, which would allow shorter names (like `build-mom5` with tags `compiler-intel@2021.1.2` and `spack_packages-2023.07.25`)

**Implementation considerations** 
* How would we search for an image that satisfies both a name and a set of tags?
* How would we search for an image that has the same name and set of tags, that is a later build? Possibly utilizing the automatic `latest` tag
* How would we search for an image that has the same name and set of tags, that is an earlier build? Can we search by date?

**Comment by CodeGat** [comment]
@echus, raised that issue we were talking about :)

**Comment by echus** [comment]
Thanks!

Have a look here: https://github.com/docker/metadata-action

I believe the metadata action gives us a build timestamp tag out of the box.

I'd suggest following the opencontainers standard for our own tags as well - e.g. `org.au.access-nri.someKey = value`.

**Comment by CodeGat** [comment]
Some difficulties with implementing this ticket as written
* Using separate `git tag`s for each variation: 
  * It isn't possible to search for an image that satisfies multiple tags - they just aren't meant to be used that way. And there is no way to find the correct image id if the tags are moved around (see below)
  * When a future image is pushed (say, `mom5`), and it uses the same variations (say, `intel@2021.1.2`, which is fairly likely), the tag will be taken from a previous version of the same `image:tag` - they must be unique. This would lead to losing information on the variants in that particular image. 
* Using a combined `git tag` for all variations:
  * When a future image is pushed, and it uses all the same variations (say, `intel@2021.1.2-2023.05.07`) the tag will be taken from a previous version of the same `image:tag` - they must also be unique. 
* Using custom `LABEL`s in the Dockerfile:
  * To `docker inspect` a images `LABEL`s, they must be local 
  * There are only workarounds to getting an images `LABEL`s without pulling the image itself down from a registry. Some of the other solutions (like `skopeo`) can only look at the labels of one image at a time, meaning a loop to find the correct variants for a single image would take a considerable amount of time (around 2s per image)
  * `LABEL`s are metadata of the image itself and are hard to find for regular people - especially if you were looking for images with the same name but differing compilers on the web interface. 

Despite this, `LABEL`s can contain important metadata that could be leveraged at some point in the future, so I think this tickets best course of action would be to add the `LABEL`s to the Dockerfiles, and keep the current convention of `build-<model>-<compiler>-<spack_packages version>`. However, if there are any future variations to the image, the name of the image would become far larger.
