### ISSUE TITLE
Remove duplication of effort in 'compiler x model' matrix

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/build-ci#83]
At the moment, the matrix pipeline is done as follows:
```
generate-matrix ---- dependency-image-pipeline ------ base-spack compiler 1 ---- dependency image model 1
                                                 |--- base-spack compiler 1 ---- dependency image model 2
                                                 |--- base-spack compiler 2 ---- dependency image model 1
                                                 |--- base-spack compiler 2 ---- dependency image model 2
```
in other words, there is duplication of effort  in the creation of the base-spack image (if it exists). This also thrashes the github actions cache and the s3 buildcache as the images are done in parallel and overwrite the cache at different points. 

The solution is simplier:
```
generate-matrix --------- base-spack compiler 1 -------- dependency image model 1
                    |                              |---- dependency image model 2
                    |---- base-spack compiler 2 -------- dependency image model 1
                                                   |---- dependency image model 2          
``` 
Instead of the matrix operation happening all at the start, it should be done in two parts - one in the compiler matrix, then one in the dependency image.                          

For a test version of the implementation, see https://github.com/CodeGat/gittest/blob/master/.github/workflows/matrix-test.yaml

**Comment by aidanheerdegen** [comment]
Is that repo private? I can't see it.

**Comment by CodeGat** [comment]
Hi @aidanheerdegen, whoops, it is private. 
As a generic example, imagine we have two dependent jobs that use matrices `x` and `y` respectively. The gist is, that we currently do this:
```
strategy:
  matrix:
    x: ['a', 'b']
    y: ['1', '2']
uses: some-cool-workflow
with:
  x: ${{ matrix.x }}
  y: ${{ matrix.y }}
```
which leads to a parallel job:
```
(a, 1)
(a, 2)
(b, 1)
(b, 2)
```
being run with `some-cool-workflow`. If we imagine `a` and `b` to be inputs to some expensive docker build operation required for later operations on matrix `y`, we note that we are duplicating the effort (and in our real world case, smashing the cache). 
A more efficient solution is to do:
```
strategy:
  matrix: 
    x: ['a', 'b']
uses: some-cool-workflow
with: 
  x: ${{ matrix.x }}
  ys: '['1', '2']'
```
and then in `some-cool-workflow` have a second matrix that uses `ys`. This looks like:
```
(a) --- (a, 1)
     |- (a, 2)
(b) --- (b, 1)
     |- (b, 2)
```
Does that make sense?

**Comment by aidanheerdegen** [comment]
Yes. I think you can achieve the same thing by, effectively, turning off the parallelism.

https://cbrgm.net/post/2022-01-12-github-actions-environments/

**Comment by CodeGat** [comment]
Fair enough, but we do still want some parallelism: `x` can be parallelized, and (once those jobs complete) so can `y`

**Comment by aidanheerdegen** [comment]
Just wanted to make sure the extra complexity was worth it. The larger the metrix the more the complexity pays off, so the right choice I think.
