### ISSUE TITLE
Software installation in current images can only be done easily using Spack

### ISSUE THREAD

**Issue by micaeljtoliveira** [ACCESS-NRI/build-ci#9]
Currently the packages get installed in directories whose name includes hashes. That means that the only practical way to use them is through Spack, i.e., one needs to do `spack load ...` before trying to use the packages in a build.

It would be nice to support other ways of building the software, for example, by using environment modules. Spack does install the module files, but they can't be used because neither lmod nor tcl modules are installed in the image.

Another way would be to install the packages as part of a Spack environment. This would provide a "view"  where all the packages are easily accessible. Better yet, check the Dockerfiles that Spack creates to automatically install an environment. It does it in a nice way that makes it very easy to use the packages and, at the same time, minimizes considerably the size of the docker images.

**Comment by CodeGat** [comment]
Closing #20 as this issue seems to cover that

**Comment by CodeGat** [comment]
Need to merge the spack_packages PR to mark as completed!

**Comment by CodeGat** [comment]
Merged!
